import { ToolItem } from "../../types";

export const toolDetails: ToolItem = {
  "id": "social-bio-gen",
  "slug": "bio-template-generator",
  "category": "social",
  "categoryName": "Social Media Tools",
  "title": "Bio Template Generator",
  "shortDesc": "Generate professional and creative bio outlines for Instagram, TikTok, and Twitter.",
  "metaDesc": "Create social media bios with our interactive template generator. Choose business, creator, freelancer tones and fill in values.",
  "instructions": [
    "Select your platform and bio style (professional, witty, casual, bulleted).",
    "Fill in the prompt fields (occupation, target audience, call to action).",
    "Click 'Generate Bios' to get a list of optimized templates.",
    "Copy and customize."
  ],
  "features": [
    "Templates optimized for Instagram (150 char limits) and TikTok (80 char limits).",
    "Interactive field inputs.",
    "Includes emojis and line-break guidelines."
  ],
  "componentName": "BioTemplateGenerator",
  "faqs": [
    {
      "question": "What is a bio template generator?",
      "answer": "A bio template generator is an interactive writing assistant that builds structured, high-converting social media profiles. By selecting a platform and filling out occupation or niche details, creators can generate optimized bios complete with line breaks, emojis, and call-to-action link prompts in seconds. This saves creators hours of writing while ensuring their profile reads polished and engaging."
    },
    {
      "question": "How do I write a professional social media bio?",
      "answer": "To write a professional bio, state clearly what you do, who your target audience is, and what value you provide, followed by a strong call-to-action prompt directing visitors to your website link. Keep the copy structured with bullet points and use relevant emojis to guide the reader's eye. This structure gives visitors a clear snapshot of who you are and why they should follow you."
    },
    {
      "question": "Can I customize generated bios?",
      "answer": "Yes, all templates generated by our tool are fully editable. You can select a template layout that fits your style, copy it to your clipboard, paste it into your profile editor, and customize the text, hashtags, or links to reflect your personality and brand goals. Feel free to swap out emojis, tweak the tone, or adjust wording to match your unique voice."
    },
    {
      "question": "Which platforms support bio templates?",
      "answer": "Our bio builder supports all major social media networks, including Instagram, TikTok, Twitter, LinkedIn, and YouTube. It automatically warns you about platform character limits, ensuring your bio copy is within the 150-character limit for Instagram or the 80-character cap for TikTok profiles. Each template is tailored to fit the specific character constraints and formatting rules of the platform you choose."
    },
    {
      "question": "Why is a strong bio important?",
      "answer": "A strong bio is important because it is the first text visitors read when landing on your page. A clear, punchy bio hook establishes trust, explains your niche value, and drives traffic to your landing page link, converting casual profile visitors into loyal followers and customers. It's often the deciding factor in whether a visitor clicks follow, scrolls past, or leaves your page entirely."
    },
    {
      "question": "How do I add line breaks in my Instagram bio?",
      "answer": "Instagram's mobile app sometimes strips standard line breaks, causing text to bundle into a messy paragraph block. To prevent this, use clean formatting buffers. Our generator inserts standard line-break guides. You can draft your bio, copy it, and paste it into Instagram. Alternatively, you can use invisible spaces or emojis to separate lines cleanly."
    },
    {
      "question": "Is this bio builder free to use?",
      "answer": "Yes, our bio generator is 100% free to use. There are no registration forms, trial periods, or limits on the number of bio layouts you can generate. You can build as many profiles as you need directly within your browser."
    }
  ],
  "seoTitle": "Social Bio Generator - Instagram, TikTok & Twitter Templates",
  "seoHeading": "Write High-Converting Social Media Bios",
  "seoIntro": "Hook your profile viewers instantly. Fill out prompt fields to draft structured bios with emojis and CTA links. Learn about the structure of a high-converting profile, platform limits, and how to drive traffic to your landing pages.",
  "seoBody": "\n<h3>Structure of a High-CTR Bio</h3>\n<p>An effective bio tells users what to expect from your content. Keep it structured with a clear statement of value, social proof or niche details, and a link prompt at the bottom. The standard formula for a high-converting profile includes:</p>\n<ol>\n  <li><strong>The Hook (Line 1):</strong> What do you do? State your niche value clearly (e.g. 'I help SaaS startups scale SEO organic traffic').</li>\n  <li><strong>Social Proof (Line 2):</strong> Why should they trust you? (e.g. 'Ex-Google Engineer', '50k+ readers').</li>\n  <li><strong>Call-to-Action (Line 3):</strong> A direct prompt guiding users to click the link below (e.g. 'Get my free guide below 👇').</li>\n</ol>\n<p>To verify that your bio text fits within character rules, use our related <a href=\"/tools/social/character-counter\">Social Character Counter</a>. If you need a custom landing page for your profile link, build one for free using our <a href=\"/tools/social/social-media-link-in-bio-helper\">Social Link-in-Bio Helper</a>.</p>\n\n<h3>Character Limits by Platform</h3>\n<p>Social networks enforce strict limits on bio profiles. Exceeding these limits will cause your text to get clipped or block updates entirely:</p>\n<ul>\n  <li><strong>Instagram:</strong> 150 characters maximum. Focus on bulleted value lines and a single link.</li>\n  <li><strong>TikTok:</strong> 80 characters maximum. This is extremely tight, so focus on a brief hook and a link indicator.</li>\n  <li><strong>Twitter/X:</strong> 160 characters maximum. A short sentence works best here.</li>\n  <li><strong>LinkedIn Summary:</strong> Up to 2,000 characters, although the profile intro card clips after 200. Place key info first.</li>\n</ul>\n\n<h3>Key Benefits of Our Bio Builder</h3>\n<ul>\n  <li><strong>Vibrant Layout Presets:</strong> Choose between professional, casual, witty, or bulleted bio styles depending on your brand voice.</li>\n  <li><strong>Interactive Field Prompts:</strong> Simply enter your occupation, target audience, and website link, and the tool builds formatted drafts instantly.</li>\n  <li><strong>100% Client-Side Private:</strong> Your inputs and drafted bios are never stored on servers, ensuring your launch campaigns remain secure.</li>\n</ul>\n\n<h3>Common Profile Writing Mistakes</h3>\n<ol>\n  <li><strong>Overusing Hashtags:</strong> Adding 5-10 clickable hashtags to your bio. This wastes valuable characters and provides visitors with exit links that redirect them away from your profile. Use at most one brand hashtag.</li>\n  <li><strong>Ignoring the Call-to-Action (CTA):</strong> Adding a link in your bio without explaining why users should click it. Always include a short prompt pointing to the link.</li>\n  <li><strong>Cluttered Paragraphs:</strong> Writing long, unspaced text blocks. Mobile users scan profiles quickly, so keep details formatted with emojis and line breaks. Style your brand name with our <a href=\"/tools/social/fancy-text-generator\">Fancy Text Generator</a>.</li>\n</ol>\n\n<h3>Official Styling Guidelines</h3>\n<p>For more profile optimization advice, read <a href=\"https://help.instagram.com/\" target=\"_blank\" rel=\"noopener noreferrer\">Instagram Account Guidelines</a> and explore marketing tips at the <a href=\"https://www.tiktok.com/creators/\" target=\"_blank\" rel=\"noopener noreferrer\">TikTok Creator Portal</a>.</p>\n    "
};
