import { ToolItem } from "../../types";

export const toolDetails: ToolItem = {
  "id": "util-qr-gen",
  "slug": "qr-code-generator",
  "category": "utility",
  "categoryName": "Utility Tools",
  "title": "QR Code Generator",
  "shortDesc": "Generate standard QR codes for URLs, text, or Wi-Fi configurations.",
  "metaDesc": "Create free custom QR codes online. Generate codes for links, text, emails, and Wi-Fi networks. Download as high-res images instantly.",
  "instructions": [
    "Choose the data type (URL, plain text, Wi-Fi config).",
    "Enter the content or login details.",
    "The QR code renders instantly.",
    "Click 'Download QR Code' to save it as a high-quality PNG."
  ],
  "features": [
    "Multi-type support: Links, text, WiFi logins.",
    "Real-time render updates.",
    "Offline browser generation."
  ],
  "componentName": "QrCodeGenerator",
  "faqs": [
    {
      "question": "What is a QR code?",
      "answer": "A QR (Quick Response) code is a two-dimensional matrix barcode developed in 1994 by the Japanese company Denso Wave. Unlike traditional linear barcodes that only read horizontally, QR codes encode information both vertically and horizontally. This allows them to store up to 100 times more data, including website links, plain text, email addresses, phone contact cards, and Wi-Fi network credentials."
    },
    {
      "question": "What is the difference between static and dynamic QR codes?",
      "answer": "A static QR code encodes the target data (like a website URL) directly into its pixel pattern. Once printed, the data cannot be edited because changing it would require changing the pixel layout. A dynamic QR code encodes a redirect short link hosted by a server. If you need to edit the target URL later, you can update the redirect endpoint on the server without changing the printed QR code's layout."
    },
    {
      "question": "How do Wi-Fi QR codes work?",
      "answer": "Wi-Fi QR codes encode network configurations using a specific syntax schema: `WIFI:S:NetworkName;T:WPA;P:Password;;`. When scanned by a modern smartphone (iOS or Android), the operating system recognizes the schema, parses the SSID, encryption type (e.g. WPA/WEP), and password, and prompts the user to join the Wi-Fi network instantly without typing passwords."
    },
    {
      "question": "Does my QR code have an expiration date?",
      "answer": "No, static QR codes generated by our tool never expire. Since the data is written directly into the pixel structure, the code will remain functional indefinitely as long as the target website URL is active or the plain text remains relevant. We do not charge fees, redirect your traffic, or track your scans."
    },
    {
      "question": "How do I format a QR code for print marketing?",
      "answer": "For print marketing materials (like business cards, brochures, packaging, and posters), ensure the QR code is printed at a resolution of at least 300 DPI (Dots Per Inch) and is at least 2cm x 2cm in size. Maintaining a high contrast (such as dark black pixels on a solid white background) ensures older mobile cameras can scan it."
    },
    {
      "question": "Can I customize the color of the QR code?",
      "answer": "Yes, you can customize QR code colors, but you must maintain a high contrast ratio between the foreground pixels and the background background. If you use light colors (like yellow or light gray) on a white background, camera sensors will struggle to distinguish the squares, rendering the code unscannable. Keep contrast high."
    },
    {
      "question": "Is this QR code builder safe for private data?",
      "answer": "Yes, our generator is completely secure. All calculations and pixel matrix maps are computed locally in your web browser using JavaScript libraries. Your Wi-Fi passwords, personal text, and target URLs are never sent over the internet or uploaded to any database, ensuring 100% confidentiality."
    },
    {
      "question": "What data types can I encode into a QR code?",
      "answer": "Our QR Code Generator supports several data types: website URLs (the most common use case), plain text (great for business card info, instructions, or event details), email addresses (opens a new email when scanned), phone numbers (opens the dialer), and SMS messages. For WhatsApp-specific scan-to-chat codes, use our dedicated WhatsApp QR Generator which formats the wa.me link automatically."
    },
    {
      "question": "What is the difference between static and dynamic QR codes?",
      "answer": "A static QR code encodes your data directly into the pixel pattern — it's permanent, free, and never expires. A dynamic QR code encodes a short redirect URL on a server; the destination can be changed later, but it requires a paid subscription and stops working if the provider shuts down. For most creators and small businesses, static QR codes are the reliable and free choice."
    },
    {
      "question": "How large should my QR code be for print?",
      "answer": "The minimum safe print size is 2 × 2 cm (about 0.8 inches). Smaller than this, older phone cameras may fail to scan reliably. For large-format printing like banners or posters, scale the downloaded PNG up proportionally and maintain a white quiet-zone margin around all four edges of the QR grid to ensure reliable scanning."
    }
  ],
  "seoTitle": "Free QR Code Generator - Create Custom QR Codes",
  "seoHeading": "Create Custom Scannable QR Codes Instantly",
  "seoIntro": "Need to share a website link, distribute a Wi-Fi password, or print scannable tags for your store? Our free online QR Code Generator creates pixel-sharp, high-resolution QR codes processed entirely in your browser — no sign-up, no watermarks, no data sent to any server.",
  "seoBody": "\n<h3>What Can You Do With a QR Code?</h3>\n<p>QR (Quick Response) codes bridge physical and digital worlds. When scanned with a smartphone camera, they instantly open URLs, display contact info, connect to Wi-Fi networks, or launch messaging apps — all without the user typing a single character. They're essential for businesses, marketers, event organisers, and content creators who want to make offline materials interactive.</p>\n\n<h3>Common QR Code Use Cases</h3>\n<ul>\n  <li><strong>Business cards:</strong> Add a QR code that opens your website, LinkedIn, or portfolio directly</li>\n  <li><strong>Restaurant menus:</strong> Link to a digital PDF menu that you can update without reprinting</li>\n  <li><strong>Marketing flyers:</strong> Drive print audiences to a landing page, signup form, or product page</li>\n  <li><strong>Product packaging:</strong> Link to instructional videos, warranty forms, or review pages</li>\n  <li><strong>Event signage:</strong> Allow attendees to scan for schedules, maps, or RSVP forms</li>\n  <li><strong>Wi-Fi sharing:</strong> Encode your Wi-Fi credentials so guests connect with a scan, no password typing</li>\n  <li><strong>WhatsApp chat:</strong> Use our <a href=\"/tools/social/whatsapp-qr-generator\">WhatsApp QR Generator</a> for pre-formatted chat links</li>\n</ul>\n\n<h3>Tips for High-Quality QR Codes</h3>\n<ul>\n  <li><strong>Minimum print size:</strong> 2 × 2 cm — smaller codes fail to scan on older cameras</li>\n  <li><strong>Always keep a white quiet zone</strong> (margin) around the code — without it scanners can't detect the boundaries</li>\n  <li><strong>Test before printing:</strong> Scan on iOS and Android at arm's length before ordering large print runs</li>\n  <li><strong>Add a call to action:</strong> Text like 'Scan to visit' increases scan rates by up to 3×</li>\n  <li><strong>Keep URLs short:</strong> Shorter URLs produce simpler QR patterns that are easier to scan — use a URL shortener if needed</li>\n</ul>\n\n<h3>100% Browser-Based — Your Data Stays Private</h3>\n<p>All QR code generation happens locally in your browser. Your URLs, text, and Wi-Fi passwords are never sent to our servers. Generate as many codes as you need without any privacy concerns.</p>\n"
};
